//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use sea_orm::{
    prelude::Decimal, ActiveModelBehavior, DeriveEntityModel, DerivePrimaryKey, DeriveRelation,
    EntityTrait, EnumIter, IdenStatic, PrimaryKeyTrait, Related, RelationDef, RelationTrait,
};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "beer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: String,
    pub brewery: String,
    pub brewery_location: String,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))")]
    pub alcohol_content: Decimal,
    #[sea_orm(column_type = "Decimal(Some((3, 2)))")]
    pub average_rating: Decimal,
    pub image_url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::review::Entity")]
    Review,
}

impl Related<super::review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Review.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
